version: '3'

services:
  frontend:
    build:
      context: C:/Users/propo/WebstormProjects/todo
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: db_todolist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: D:/documents/JavaLabs/ToDoList
      dockerfile: Dockerfile
    ports:
      - "8080:8080"


    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_todolist
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}